# Generated by Django 4.2.7 on 2025-12-01 07:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, default='', max_length=120)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('current_location', models.CharField(blank=True, default='', max_length=150)),
                ('vehicle_type', models.CharField(blank=True, default='', max_length=30)),
                ('vehicle_number', models.CharField(blank=True, default='', max_length=30)),
                ('emergency_contact1_name', models.CharField(blank=True, default='', max_length=120)),
                ('emergency_contact1_phone', models.CharField(blank=True, default='', max_length=20)),
                ('emergency_contact1_relation', models.CharField(blank=True, default='', max_length=60)),
                ('emergency_contact2_name', models.CharField(blank=True, default='', max_length=120)),
                ('emergency_contact2_phone', models.CharField(blank=True, default='', max_length=20)),
                ('emergency_contact2_relation', models.CharField(blank=True, default='', max_length=60)),
                ('bank_account_number', models.CharField(blank=True, default='', max_length=24)),
                ('bank_account_holder', models.CharField(blank=True, default='', max_length=120)),
                ('bank_name', models.CharField(blank=True, default='', max_length=120)),
                ('ifsc_code', models.CharField(blank=True, default='', max_length=11)),
                ('upi_id', models.CharField(blank=True, default='', max_length=60)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='delivery/profile_images/')),
                ('joined_date', models.CharField(blank=True, default='', max_length=40)),
                ('total_deliveries', models.IntegerField(blank=True, default=0, null=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=3, null=True)),
                ('completion_rate', models.CharField(blank=True, default='', max_length=20)),
                ('response_time', models.CharField(blank=True, default='', max_length=20)),
                ('average_rating', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=3, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
