# Generated by Django 5.2.8 on 2025-11-29 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_doctorprofile_address_doctorprofile_city_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DoctorProfile',
        ),
    ]
